In [91]:
import os
import matplotlib.pyplot as plt
import librosa, librosa.display
import IPython.display as ipd
import numpy as np

In [92]:
audio_dir = "C:\\Users\\Minh\\Desktop\\Audio_Attr\\WAV files/sprayer2.wav"
audio, sr = librosa.load(audio_dir, duration = 7)

In [93]:
X = np.fft.fft(audio)
X_mag = np.absolute(X)

f = np.linspace(0, sr, len(X_mag))
f_bins = int(len(X_mag))  

#print(f)
print(X_mag.size)
#plt.plot(f[:f_bins], X_mag[:f_bins])
f[:f_bins], X_mag[:f_bins]

#print(f)
#print(X_mag)
#print(f.size)
#print(f_bins)

154350


(array([0.00000000e+00, 1.42858068e-01, 2.85716137e-01, ...,
        2.20497143e+04, 2.20498571e+04, 2.20500000e+04]),
 array([0.39036866, 0.27135263, 0.15180892, ..., 0.1343992 , 0.15180892,
        0.27135263]))

In [94]:
freq =[] #Freq là mảng ghi tần số có mức độ xuất hiện lớn nhất
freq = [0 for i in range(7)]

magnitude =[] #Magnitude là cụ thể mức độ xuất hiện là bao nhiêu
magnitude = [0 for i in range(7)]

position = 0
max = 0
pos = 0

for i in range(0, len(X_mag)):        
    if(X_mag[i] > max):
        max = X_mag[i]
        pos = i
    if(i> 0):
        if( (i % int(len(X_mag)/7)) == 0 and i != len(X_mag)-1):            
            freq[position] = pos
            magnitude[position] = max
            #print('Position value at checkpoint: ' + str(position))
            position += 1
            max = 0
        if(i == len(X_mag)-1):            
            freq[position] = pos
            magnitude[position] = max
            #print('Position value at checkpoint: ' + str(position))  
   

32.775026266862746
[7009, 41161, 45355, 86851, 108995, 113189, 147341]
[32.77502626686275, 41.269705472980164, 34.10496374482349, 25.449058561994548, 34.104963744823486, 41.26970547298015, 32.775026266862746]
[0.39036866 0.27135263 0.15180892 ... 0.1343992  0.15180892 0.27135263]
